### ISSUE TITLE
2.8.0-rc2: Makefile parallelization bugs

### ISSUE THREAD

**Issue by mkoeppe** [wbhart/flint2#981] opened 2021-07-16 16:58 UTC
I'm getting this on a highly parallelized build (make -j12)
```
[flint-2.8.0-rc2] gcc -fPIC -fno-common -O2 -g -march=native -I/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/.tox/local-homebrew-macos-minimal/local/var/tmp/sage/build/flint-2.8.0-rc2/src -I/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/.tox/local-homebrew-macos-minimal/local/var/tmp/sage/build/flint-2.8.0-rc2/src/build -I/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/.tox/local-homebrew-macos-minimal/local/include -I/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/.tox/local-homebrew-macos-minimal/local/include -I/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/.tox/local-homebrew-macos-minimal/local/include -c sort.c -o ../build/fmpz_mod_mpoly_factor/sort.lo -MMD -MP -MF "../build/fmpz_mod_mpoly_factor/sort.d" -MT "../build/fmpz_mod_mpoly_factor/sort.d" -MT "../build/fmpz_mod_mpoly_factor/sort.lo"
[flint-2.8.0-rc2] gcc -fPIC -fno-common -O2 -g -march=native -I/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/.tox/local-homebrew-macos-minimal/local/var/tmp/sage/build/flint-2.8.0-rc2/src -I/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/.tox/local-homebrew-macos-minimal/local/var/tmp/sage/build/flint-2.8.0-rc2/src/build -I/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/.tox/local-homebrew-macos-minimal/local/include -I/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/.tox/local-homebrew-macos-minimal/local/include -I/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/.tox/local-homebrew-macos-minimal/local/include -c stack.c -o ../build/fmpz_mod_mpoly_factor/stack.lo -MMD -MP -MF "../build/fmpz_mod_mpoly_factor/stack.d" -MT "../build/fmpz_mod_mpoly_factor/stack.d" -MT "../build/fmpz_mod_mpoly_factor/stack.lo"
[flint-2.8.0-rc2] gcc -fPIC -fno-common -O2 -g -march=native -I/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/.tox/local-homebrew-macos-minimal/local/var/tmp/sage/build/flint-2.8.0-rc2/src -I/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/.tox/local-homebrew-macos-minimal/local/var/tmp/sage/build/flint-2.8.0-rc2/src/build -I/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/.tox/local-homebrew-macos-minimal/local/include -I/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/.tox/local-homebrew-macos-minimal/local/include -I/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/.tox/local-homebrew-macos-minimal/local/include -c zip_helpers.c -o ../build/fmpz_mod_mpoly_factor/zip_helpers.lo -MMD -MP -MF "../build/fmpz_mod_mpoly_factor/zip_helpers.d" -MT "../build/fmpz_mod_mpoly_factor/zip_helpers.d" -MT "../build/fmpz_mod_mpoly_factor/zip_helpers.lo"
[flint-2.8.0-rc2] 2 warnings generated.
[flint-2.8.0-rc2] error: error opening '../build/fmpz_mod_mpoly_factor/sort.d': No such file or directory
[flint-2.8.0-rc2] 1 error generated.
[flint-2.8.0-rc2] error: error opening '../build/fmpz_mod_mpoly_factor/polyun.d': No such file or directory
[flint-2.8.0-rc2] 1 error generated.
[flint-2.8.0-rc2] make[6]: *** [../build/fmpz_mod_mpoly_factor/sort.lo] Error 1
[flint-2.8.0-rc2] make[6]: *** Waiting for unfinished jobs....
[flint-2.8.0-rc2] make[6]: *** [../build/fmpz_mod_mpoly_factor/polyun.lo] Error 1
[flint-2.8.0-rc2] make[5]: *** [libflint-16.dylib] Error 2
[flint-2.8.0-rc2] make[4]: *** [library] Error 2
[flint-2.8.0-rc2] make[3]: *** [verbose] Error 2
```

**Comment by wbhart** [comment] 2021-07-16 18:05
That's the dependency tracking. I don't think there's anything we can do
about that. It's caused by a broken toolchain as far as I know.

**Comment by mkoeppe** [comment] 2021-07-16 18:37
We haven't run into this issue in previous versions of FLINT 2.8. Other packages allow to say `configure --disable-dependency-tracking`, which usually improves robustness for parallel builds.
Using the cmake build system may be an option for us -- is it ready for general use in FLINT 2.8?

**Comment by wbhart** [comment] 2021-07-16 18:56
That's interesting. I wonder what we could have changed since the last version. All of the dependency tracking stuff is more or less automatic.

Certainly fmpz_mod_mpoly_factor is a new module since last time, so it seems like it isn't doing dependency tracking for that. But if you look in Makefile.subdirs, there is nothing specific to that directory. It's all completely generic. Similarly the main Makefile doesn't special case that directory. It's also completely generic. So it's a mystery what we could have done to break it.

Anyhow, CMake is tested in our CI. I wouldn't expect any problems with it.

**Comment by wbhart** [comment] 2021-07-16 18:57
Unfortunately we don't have an option to turn off dependency tracking. I think that would be quite difficult to hack in, but I'll open a ticket for it, in case we ever have a brilliant Makefile expert who wants to hack that in some day.

**Comment by wbhart** [comment] 2021-07-22 13:10
I'll close this in favour of the ticket #982 

As far as I can see given that parallel builds clearly work on other platforms I think it's a toolchain issue. We may do a 2.8.1 to fix this at some point. I don't feel confident fiddling with the build system to fix it myself right now without breaking the build for others.

**Closed by wbhart** 2021-07-22 13:10 UTC
