### ISSUE TITLE
Error in fmpz_poly_factor(?)

### ISSUE THREAD

**Issue by thofma** [wbhart/flint2#344] opened 2017-07-27 08:41 UTC
@wbhart 

Get the polynomial at http://www.mathematik.uni-kl.de/~thofmann/fac_error.txt

Then
```julia
julia> using Nemo

julia> include("/home/thofmann/fac_error.txt");

julia> factor(f)
ERROR: DivideError: integer division error
 in _factor(::Nemo.fmpz_poly) at /home/thofmann/.julia/v0.5/Nemo/src/flint/fmpz_poly.jl:620
 in factor(::Nemo.fmpz_poly) at /home/thofmann/.julia/v0.5/Nemo/src/flint/fmpz_poly.jl:608

julia> fac = Nemo.fmpz_poly_factor()
Nemo.fmpz_poly_factor(1,Ptr{Nemo.fmpz_poly} @0x0000000000000000,Ptr{Int64} @0x0000000000000000,0,0)

julia> ccall((:fmpz_poly_factor, :libflint), Void, (Ptr{Nemo.fmpz_poly_factor}, Ptr{fmpz_poly}), &fac, &f)
ERROR: DivideError: integer division error
 in anonymous at ./<missing>:?
```

**Comment by wbhart** [comment] 2017-08-21 11:23
I ran the following simple C program,

#include "flint.h"
#include "fmpz.h"
#include "fmpz_poly.h"

int main(void)
{
   FILE * file = fopen("/home/wbhart/fac_error.txt", "r");
   fmpz_poly_t poly;
   fmpz_poly_factor_t fac;
   char * x = flint_malloc(10);

   fmpz_poly_init(poly);
   fmpz_poly_factor_init(fac);

   fmpz_poly_fread_pretty(file, poly, &x);
   printf("here1\n");
   fmpz_poly_factor(fac, poly);
   printf("here2\n");

   fmpz_poly_clear(poly);
   fmpz_poly_factor_clear(fac);

   fclose(file);
   flint_cleanup();

   printf("here\n");

   return 0;
}

Oddly enough, valgrind finishes before the divide by zero error is raised.
But the error certainly occurs in the factor function.

**Comment by wbhart** [comment] 2017-08-21 13:03
The problem is in fmpz_poly_CLD_bounds.

It evaluates a certain polynomial at r and 1/r for various values of r. In
this case, r just gets so huge it overflows a double. I think the algorithm
is from a published paper, so either there is a bug (which I can't seem to
find at present), or the algorithm has a serious flaw in practice.

As far as I can tell, the algorithm isn't actually doing the wrong thing.
The upper and lower evaluations are getting closer with each iteration.
It's just that the value r that the polynomials are being evaluated at in
fmpz_poly/CLD_bounds.c using fmpz_poly_evaluate_horner_d_2exp becomes too
large (its exponent overflows the maximum exponent a double can have).

**Comment by wbhart** [comment] 2017-08-21 13:51
I think the algorithm is correct. The polynomial is just so huge that the
needed evaluation point overflows a double.

This is highly nontrivial to fix. We would need to
implement fmpz_poly_evaluate_horner_d_2exp_2exp, which would evaluate at a
double r, scaled by a long exponent, r_exp, say. Then we'd need to put code
throughout the CLD_bounds function to detect the need for this case (r gets
too large), and switch over to updating r and its exponent r_exp instead of
just r.

**Comment by wbhart** [comment] 2017-08-21 13:52
Actually, even detecting when this case is about to occur so that a flint
exception can be raised is already messy. I think it is better to spend the
time on just fixing the function itself.

**Comment by thofma** [comment] 2017-08-21 21:24
Thanks for looking into this. What are actually these CLD_bounds?

**Comment by wbhart** [comment] 2017-08-21 22:10
They are described in our paper:

https://www.math.fsu.edu/~hoeij/papers/issac11/A.pdf

**Comment by fredrik-johansson** [comment] 2018-11-20 16:17
There is a possible fix in https://github.com/fredrik-johansson/flint2/tree/CLDbug

It seems to make this factorization pass, but I don't know if the factorization is actually correct.

There are several problems with this code. The termination criterion is supposed to be that the high and low bounds agree to within a factor 2. I think the numerical search isn't guaranteed to this level of accuracy when r is very large.  I added another criterion that just checks if the *exponents* agree to within a factor 1.5 which makes it succeed at least on this example, bu t I don't know if this is actually correct...

The CLD_bound test code fails if the rbits > 200 test is lowered. I don't know if this is because the CLD_bound test is too strict (checking that the bound is more accurate than it needs to be) or because the new version of the code is wrong...

fmpz_poly_evaluate_horner_d_2exp is also implemented quite inefficiently, but that's not a critical issue.

**Comment by wbhart** [comment] 2020-01-23 22:39
Fixed in trunk.

**Closed by wbhart** 2020-01-23 22:39 UTC
