### ISSUE TITLE
acb_hypgeom_2f1 segfaults on mips64el for certain inputs

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#699] opened 2020-05-09 11:47 UTC
Hi, here is a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=953437) I received about flint segfaulting on mipsel ; it comes with a simple example showing the problem.

(reminder : I'm the maintainer of the Debian package for flint & arb)

**Comment by wbhart** [comment] 2020-05-09 15:36
Thanks for the report. The cause (and solution) don't immediately jump out at me. We will investigate.

**Comment by fredrik-johansson** [comment] 2020-05-09 16:02
Unfortunately, the test program valgrinds cleanly for me.

**Comment by wbhart** [comment] 2020-05-10 23:45
I think this problem will go away if you drop back to GMP 6.1. We do not currently properly support GMP 6.2, but are working on it.

**Comment by SnarkBoojum** [comment] 2020-05-11 06:33
I tried to reproduce the problem, and it worked too - and with gmp 6.2, so there's something more to find out here : let's see if the original reporter can find out more about the issue.

**Comment by fredrik-johansson** [comment] 2020-05-11 08:02
Indeed, that the segfault occurs when assigning to r->_mp_d[0] suggests a problem caused by the lazy initialization in GMP 6.2.

A good first step would be to do a thorough review of gmpcompat.h; for example, in functions like flint_mpz_set_si, we need to check that the output has allocated limbs.

**Comment by wbhart** [comment] 2020-05-11 08:30
Right, and we'll also need to look at all cases in Flint where _mp_d is accessed.

**Comment by wbhart** [comment] 2020-05-14 16:01
@SnarkBoojum I have made an attempt to fix this. Perhaps your contributor could test the latest trunk branch to see if the issue is gone. If you could report any compile errors or failed tests to us that would be helpful. I cannot go poking around the GMP code to work out how this should be done, so we have to pretty much guess based on feedback from others.

**Comment by SnarkBoojum** [comment] 2020-05-14 19:45
I have added a comment asking this on the Debian bug ; let's hope the user will be able to give us feedback on the matter.

**Comment by wbhart** [comment] 2020-05-14 20:04
Thanks. I very much appreciate it.

**Comment by wbhart** [comment] 2020-05-15 03:23
Looks like we didn't get this right first time around. I've pushed some more changes which according to someone else fix the GMP issues at least, and therefore hopefully this bug. But the contributor will need to pull the latest commit on trunk, not flint-2.6-alpha1.

If everything is ok this will be in alpha2.

**Comment by wbhart** [comment] 2020-05-18 22:50
I'm closing this issue, since we are fairly sure it's fixed. The symptoms match exactly.

**Closed by wbhart** 2020-05-18 22:50 UTC

**Comment by SnarkBoojum** [comment] 2020-05-19 08:02
Which commit is supposed to fix this? I would like to check.

**Comment by wbhart** [comment] 2020-05-19 13:23
The first two changes in https://github.com/wbhart/flint2/commit/369ea4522fe4347563413074e451da09199a6ffd

**Comment by SnarkBoojum** [comment] 2020-05-27 11:25
This issue should be reopened since those changes have been reverted.

**Comment by SnarkBoojum** [comment] 2020-05-27 11:53
Ah, no, the changes have been partially reverted : it's a refining.

And I looked in trunk... which wasn't the right place.
