### ISSUE TITLE
Hanging tests on VS 2019?

### ISSUE THREAD

**Issue by BrianGladman** [wbhart/flint2#675] opened 2020-04-28 23:00 UTC
I understand that the Flint MSVC Windows build used to be based on my build system but that this is no longer true - the Cmake build is now self standing.   If this is correct, it is odd that the Appveyor continuous integration script still seems to use my build system and won't hence be testing the Cmake build output.   And it won't even be testing my current build since it appears to be out of date.

**Comment by wbhart** [comment] 2020-04-28 23:05
Perhaps @isuruf can comment on this. Is the .appveyor_msvc_build file still used, or can we delete it? Same question for the .appveyor_msys_build file.

If it is using this file and hence @BrianGladman 's files, why do they pass and yet his do not?

**Comment by isuruf** [comment] 2020-04-28 23:12
Yes, the following files can be deleted,
- .appveyor_msvc_build.cmd
- .appveyor_msys_build.sh
- .build_dependencies.cmd

**Comment by wbhart** [comment] 2020-04-28 23:26
Are there any special compatibility options that are being passed to MSVC that could explain the hangs and crashes @BrianGladman sees with his build files? @BrianGladman we are using VS 2017. Could that be the explanation?

**Comment by isuruf** [comment] 2020-04-28 23:35
Nothing special I can see. `MEMORY_MANAGER` is reentrant, `HAVE_TLS` is turned on.
MPIR build is a `generic` build though.

**Comment by wbhart** [comment] 2020-04-29 06:40
Ah it could be that we set flint_test_multiplier to 1 for the CMake build. Unfortunately we can't set it to 10 without it causing timeout on Appveyor I think.

**Comment by BrianGladman** [comment] 2020-04-29 07:28
I am using VS 2019 with a fully optimised MPIR (skylake_avx) so the differences here could easily be the cause of the different behaviour.  The MEMORY_MANAGER and HAVE_TLS options may also be different.

**Comment by BrianGladman** [comment] 2020-04-29 08:13
I have been building without REENTRANT and HAVE_TLS so I will try again with these options set.

**Comment by wbhart** [comment] 2020-04-29 09:06
I believe TLS works fine on MSVC, so that option should be set anyway (it can potentially cause issues if it is not set, and I think the usual memory manager relies on it anyway, so I'm amazed anything worked at all without it). But there could be other issues of course.

**Comment by BrianGladman** [comment] 2020-04-29 11:52
The two tests for which there were access violations now work but all the tests that I reported as hanging are still doing so.     I am using VS 2019 so this seems likely to be the reason for the different test results.

**Comment by wbhart** [comment] 2020-04-29 12:00
Could you change flint_test_multiplier to 1 in test_helpers.c and see if the hangs go away. If so then we do actually have a problem that only shows up with higher test iterations.

**Comment by BrianGladman** [comment] 2020-04-29 14:52
The good news (?) is that the output is the same - all the tests that hand still do.

**Comment by wbhart** [comment] 2020-04-29 21:18
Probably the simplest one is fmpz_smod. If we can find out why it hangs, maybe we can figure them all out. I'll take a close look today.

Could you make a complete list of all hanging tests on this ticket? I believe there are some tests that take over a minute, so to exclude those could you set the timeout to 5 minutes just to be sure to distinguish those (though we can also lower the iterations on some of the others).

**Comment by BrianGladman** [comment] 2020-04-29 21:34
Should I restore the test_multiplier first or leave it at 1?

**Comment by wbhart** [comment] 2020-04-29 21:40
If the same tests are hanging then 1 is fine. That's what we use for CMake.

**Comment by BrianGladman** [comment] 2020-04-30 11:30
Here is the list of tests that don't complete in VS2019 in less than five minutes:

fmpq_mpoly: t-gcd
fmpq_mpoly: t-gcd_cofactors
fmpz_mod_poly: t-compose_mod_brent_kung_vec_preinv_threaded
fmpz_mpoly: t-divides
fmpz_mpoly: t-divides_heap_threaded
fmpz_mpoly: t-gcd
fmpz_mpoly: t-gcd_berlekamp_massey_threaded
fmpz_mpoly: t-gcd_brown_threaded
fmpz_mpoly: t-gcd_cofactors
fmpz_mpoly: t-mpolyuu_divides_threaded
fmpz_mpoly: t-mul
fmpz_mpoly: t-mul_array_threaded
fmpz_mpoly: t-mul_heap_threaded
fmpz_poly: t-taylor_shift_divconquer
nmod_mpoly: t-divides
nmod_mpoly: t-divides_heap_threaded
nmod_mpoly: t-gcd
nmod_mpoly: t-gcd_brown_threaded
nmod_mpoly: t-gcd_cofactors
nmod_mpoly: t-mpolyn_divides_threaded
nmod_mpoly: t-mul
nmod_mpoly: t-mul_array_threaded
nmod_mpoly: t-mul_heap_threaded
qsieve: t-factor
thread_pool: t-thread_pool

I am happy to help by doing some investigative work. But it would be useful to have your advice on which of these tests would be a sensible one on which to start.

**Comment by wbhart** [comment] 2020-04-30 12:14
Thanks Brian. Every single one of these tests is threaded. So something is definitely wrong with the threading.

The simplest one to look at is t-thread_pool, one assumes. All the others rely on the thread_pool. I am sure @tthsqe12 will be interested in this list.

It's interesting that fmpz/t-smod is no longer on the list. Did that really take more than a minute to complete?

It's possible that no threading actually happens on Appveyor. Perhaps @isuruf knows whether that is the case.

**Comment by wbhart** [comment] 2020-04-30 12:15
I should mention that some of the threaded tests must be passing. E.g. there are some threaded tests in nmod_poly and nmod_poly_factor which don't appear in the list.

**Comment by wbhart** [comment] 2020-04-30 12:17
And the ones in fmpz_mod_poly and fmpz_mod_poly factor also aren't on the list. So whatever we did there is correct, as compared to what we did in all the others.

**Comment by BrianGladman** [comment] 2020-04-30 12:19
Thanks Bill, I'll go through my settings to check on those that impact on threading to see if I have missed anything.

**Comment by wbhart** [comment] 2020-04-30 12:22
@BrianGladman It's worth checking that fmpz/fmpz.c is linked to (or is a copy of) fmpz/link/fmpz_reentrant.c and not one of the other files in fmpz/link. That could certainly explain it.

**Comment by BrianGladman** [comment] 2020-04-30 12:44
Ok, I think you have found the issue.  I am not using a recursive directory search for source files so the files in link won't be picked up for inclusion (should it build without any of these?).  Anyway, leave this with me for the present as its not worth more work until I have checked this out.

**Comment by wbhart** [comment] 2020-04-30 12:53
The files in fmpz/link should not be compiled in. Instead fmpz/fmpz.c should be a link to fmpz/link/fmpz_reentrant.c, or just a direct copy of it (and then fmpz/fmpz.c should be compiled as usual). Our configure takes care of this on Linux (and CMake).

[In theory, linking to fmpz/link/fmpz_single.c instead should actually work, so long as HAVE_REENTRANT is set to 0 and HAVE_TLS is set to 1 in flint-config.h. But theory and practice often diverge.

It is much easier to get Flint to work on Windows in reentrant mode, rather than single mode, in which case you have HAVE_REENTRANT set to 1 and HAVE_TLS set to 1 and fmpz/fmpz.c linked to fmpz/link/fmpz_reentrant.c.

In theory all options are supposed to work. But it has become impossible with the increasing sophistication of Flint to make all options work on all platforms, especially when TLS is not available.]

**Comment by wbhart** [comment] 2020-04-30 12:55
I should mention that single mode is faster, but it does push the threading technology a bit harder. It works on Linux ok, but I don't know if I've implemented it correctly on Windows or not.

**Comment by BrianGladman** [comment] 2020-04-30 14:57
Sadly the configuration issue, although present, is not the cause of the issue.   After correcting it and rebuilding, the test run is now underway; it has not completed yet but, half way through, all the same tests are hanging and it seems pretty certain that it will end up with the same list.

**Comment by BrianGladman** [comment] 2020-04-30 16:11
The tests that time out are the same as those listed above.   In t-threadpool.c the tests hang on the first test at line 80 where the main thread calls thread_pool_wait(). This call never returns.  The total memory usage cycles regularly up and down over a short cycle of about five seconds.  I have not dug down into flint itself but it looks as if I might now have to do this to get further.

**Comment by BrianGladman** [comment] 2020-05-01 09:35
Here is where I am with debugging t-threadpool.c   The worker threads are created without any issues and the worker threads all run.  But while they are running pthreads is stuck in mutex_lock waiting on a single event that never happens. For a reason that I haven't been able to track down, it not being given an opportunity to claim access to the protected items.

**Comment by tthsqe12** [comment] 2020-05-01 10:09
Can you try putting
`pthread_mutex_lock(&T->mutex);` at line 18
`pthread_mutex_unlock(&T->mutex);` on line 30 at the end of the fxn
in `thread_pool_wait`?

The access to the thread pool object should probably be guarded as you will find it done correctly in
`thread_pool_wake`.

**Comment by BrianGladman** [comment] 2020-05-01 10:41
Sadly this does not fix the issue.  It would be useful to eliminate pthreads as a source of problems. Is there anyone who builds with CMake who could ship me a Windows x64 pthreads static library that I could test in place of mine to see  it this fixes the issue. This would avoid us spending  lot of time chasing a Flint problem that isn't. there.

**Comment by tthsqe12** [comment] 2020-05-01 10:56
Ok. That is sad.

**Comment by BrianGladman** [comment] 2020-05-01 14:47
I am now fairly confident that the problem is a pthreads issue, not a flint one.  I'll report back after some further work on this.

**Comment by isuruf** [comment] 2020-05-01 15:11
Here's what we use with CMake. https://anaconda.org/conda-forge/pthreads-win32/2.9.1/download/win-64/pthreads-win32-2.9.1-hfa6e2cd_3.tar.bz2

**Comment by BrianGladman** [comment] 2020-05-02 20:52
First of all my thanks to tthsqe12 and isuruf for their efforts in helping me with this issue.  Here is where I am after quite a lot of effort.  Firstly I have rebuilt and tested all the libraries (static and dll) that flint uses. All tests pass in all libraries (but pthreads passed only after disabling optimisation).  I then built the flint static and dll libraries.  Both exhibit the hanging tests that I described above.  I then isolated the t-threadpool.c  test for detailed examination.  This also hangs when built with static and DLL libraries.   Isuru kindly provided the pthreads version used in the CMake build and this included the actual DLL used.    So I substituted this in place of my DLL, hoping that the problem would not be present. But, disappointingly, this also hangs.    Its difficult to figure out where to go next!

**Comment by isuruf** [comment] 2020-05-02 20:58
Can you try with the MPIR and MPFR builds that we use with CMake as well?

MPIR - https://anaconda.org/conda-forge/mpir/2.7.2/download/win-64/mpir-2.7.2-vc14_3.tar.bz2
MPFR - https://anaconda.org/conda-forge/mpfr/4.0.1/download/win-64/mpfr-4.0.1-h2fa13f4_1000.tar.bz2

They are built from your Visual Studio solutions, but might be different to the versions that you use.

**Comment by BrianGladman** [comment] 2020-05-02 21:38
I am concentrating on getting the t-treadpool.c test working since it seems likely that this is where the problem lies.  It is also much faster to focus on a single test at this point.

I noticed today that the CMake uses DLL's rather than static libraries so in running the threadpool test I am also now using the DLL libraries (I was previously testing with static libraries).   

Substituting all three DLLs from the builds you have supplied does not change the behaviour of the threadpool test - it still hangs.   

Now there is only one DLL left to swap - flint itself!

**Comment by wbhart** [comment] 2020-05-03 10:09
@BrianGladman We just fixed a bug in trunk which almost certainly could cause the issues you are seeing. Perhaps you could try again with the latest trunk and see if the issue is gone for you.

**Comment by BrianGladman** [comment] 2020-05-03 13:53
All tests now pass!  Thanks to all for helping with this issue. I should say it has not been a fruitless hunt since it has allowed me to tidy up a lot of my build generating code. It is still a bit of a hack in places but a bit less so now!

**Comment by wbhart** [comment] 2020-05-03 16:14
Great news Brian! Thanks very much for your help and feedback!

**Comment by wbhart** [comment] 2020-05-03 16:16
Fixed in trunk.

**Closed by wbhart** 2020-05-03 16:16 UTC
