### ISSUE TITLE
Tarballs for 2.8.1 on website and GitHub differ

### ISSUE THREAD

**Issue by fingolfin** [wbhart/flint2#1006] opened 2021-10-14 22:17 UTC
I just noticed that the flint 2.8.1 tarball on the website differs from that on GitHub / what's in the tag. First off, the 2.8.1 info is missing in `NEWS`. More importantly, though, `configure` differs: on the website, it still has `FLINT_PATCH=0` which affects shared library versioning...

**Comment by wbhart** [comment] 2021-10-15 10:52
I went through the same procedure to recreate the tarballs and for reasons I don't understand, the same thing happens. Things I have checked:

* the make dist command is correct
* I have run configure locally
* the tarballs created contain 2.8.1, correct versioning, changes to Makefile.subdirs, correct 2.8.1 updates to NEWS
* the link on the website is for the correct file
* I am uploading the right tarballs to the website
* I am putting them in the right directory on the web server

* When I download the tarballs from the website, they are for some other git commit.

Impossible, I know. But there doesn't seem to be anything I can do about this. I don't have the ability to debug website technology which can change contents of a tarball.

**Comment by fingolfin** [comment] 2021-10-15 11:42
Isn't the crucial question: which commit was used by your scripts? Presumably it should be the commit with tag `v2.8.1` here on GitHub, which is e3ef7bc1fa9b89f2df72fa6501cac21f518e6f15. Does that match what you have locally?

**Comment by orlitzky** [comment] 2021-10-21 12:34
> Yeah so my sha256 function doesn't work then.
> 
> Add that to the problem with my delete key no longer working and I think I'm done for today. Back at it next week.

I once spent a year thinking I was crazy that turned out to be a bad stick of RAM. Might want to give memtest86 a try =)

**Comment by wbhart** [comment] 2022-04-25 14:40
I vaguely recall https://github.com/wbhart/flint2/issues/1073 had something to do with it.

I think I was setting the version in configure, then checking it in the downloaded tarball in flint.h. As the latter had inexplicably not been updated at any of the recent releases, this was probably the underlying issue.

The issue with GitHub itself was a little harder to explain. But I vaguely recall it also had an explanation. I encountered a similar issue that someone had reported elsewhere in another context and this seemed a likely candidate as the cause of the reports we received. I don't recall those details though.

Anyhow, for now I will close this issue, as I think it will be resolved by https://github.com/wbhart/flint2/issues/1073

Of course the delete key is now working after some driver got updated, and the sha is no doubt still broken, which is why I don't use sha for such purposes.

**Closed by wbhart** 2022-04-25 14:40 UTC
