### ISSUE TITLE
fmpq_dedekind_sum_coprime_d undefined

### ISSUE THREAD

**Issue by jamesjer** [wbhart/flint2#690] opened 2020-05-06 15:45 UTC
The flintxx tests fail to compile with git head (attempted on an x86_64 Fedora Rawhide machine with gcc-10.0.1-0.12.fc33.x86_64):
```
In file included from /builddir/build/BUILD/flint2/arithxx.h:15,
                 from test/t-arithxx.cpp:14:
/builddir/build/BUILD/flint2/arithxx.h: In function 'double flint::dedekind_sum_coprime_d(double, double)':
/builddir/build/BUILD/flint2/arith.h:190:38: error: 'fmpq_dedekind_sum_coprime_d' was not declared in this scope; did you mean 'dedekind_sum_coprime_d'?
  190 | #define arith_dedekind_sum_coprime_d fmpq_dedekind_sum_coprime_d
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/flint2/arithxx.h:315:13: note: in expansion of macro 'arith_dedekind_sum_coprime_d'
  315 |     {return arith_dedekind_sum_coprime_d(h, k);}
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /builddir/build/BUILD/flint2/flintxx/evaluation_tools.h:23,
                 from /builddir/build/BUILD/flint2/flintxx/expression.h:22,
                 from /builddir/build/BUILD/flint2/fmpqxx.h:19,
                 from /builddir/build/BUILD/flint2/fmpq_polyxx.h:21,
                 from /builddir/build/BUILD/flint2/arithxx.h:17,
                 from test/t-arithxx.cpp:14:
/builddir/build/BUILD/flint2/arithxx.h: In instantiation of 'static void flint::rules::binary_expression<T, flint::operations::dedekind_sum_coprime_large_op, U, typename flint::mp::enable_if<flint::mp::and_<flint::flint_classes::is_source_base<flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data> >::type<T>, flint::flint_classes::is_source_base<flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data> >::type<U> > >::type>::doit(V&, const T&, const U&) [with V = flint::fmpqxx_expression<flint::operations::immediate, flint::detail::fmpq_data>; T = flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>; U = flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>]':
/builddir/build/BUILD/flint2/flintxx/default_rules.h:98:24:   required from 'static void flint::rules::rdetail::binary_expr_helper<BE, Data1, Op, Data2>::doit(const data_t&, flint::rules::rdetail::binary_expr_helper<BE, Data1, Op, Data2>::temporaries_t, Return*) [with Return = flint::fmpqxx_expression<flint::operations::immediate, flint::detail::fmpq_data>; BE = flint::rules::binary_expression; Data1 = const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&; Op = flint::operations::dedekind_sum_coprime_large_op; Data2 = const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&; flint::rules::rdetail::binary_expr_helper<BE, Data1, Op, Data2>::data_t = flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> >; flint::rules::rdetail::binary_expr_helper<BE, Data1, Op, Data2>::temporaries_t = flint::empty_tuple]'
/builddir/build/BUILD/flint2/flintxx/expression.h:76:26:   required from 'static void flint::detail::evaluation_traits<Operation, Expr, Data>::evaluate_into_fresh(flint::detail::evaluation_traits<Operation, Expr, Data>::evaluation_return_t&, const derived_t&) [with Operation = flint::operations::dedekind_sum_coprime_large_op; Expr = flint::expression<flint::derived_wrapper<flint::fmpqxx_expression>, flint::operations::dedekind_sum_coprime_large_op, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > >; Data = flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> >; flint::detail::evaluation_traits<Operation, Expr, Data>::evaluation_return_t = flint::fmpqxx_expression<flint::operations::immediate, flint::detail::fmpq_data>; flint::detail::evaluation_traits<Operation, Expr, Data>::derived_t = flint::fmpqxx_expression<flint::operations::dedekind_sum_coprime_large_op, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > >]'
/builddir/build/BUILD/flint2/flintxx/expression.h:49:28:   required from 'static flint::detail::evaluation_traits<Operation, Expr, Data>::evaluation_return_t flint::detail::evaluation_traits<Operation, Expr, Data>::evaluate(const derived_t&) [with Operation = flint::operations::dedekind_sum_coprime_large_op; Expr = flint::expression<flint::derived_wrapper<flint::fmpqxx_expression>, flint::operations::dedekind_sum_coprime_large_op, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > >; Data = flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> >; flint::detail::evaluation_traits<Operation, Expr, Data>::evaluation_return_t = flint::fmpqxx_expression<flint::operations::immediate, flint::detail::fmpq_data>; flint::detail::evaluation_traits<Operation, Expr, Data>::derived_t = flint::fmpqxx_expression<flint::operations::dedekind_sum_coprime_large_op, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > >]'
/builddir/build/BUILD/flint2/flintxx/expression.h:275:37:   required from 'typename flint::traits::make_const<typename flint::detail::evaluation_traits<Operation, flint::expression<Derived, Operation, Data>, Data>::evaluation_return_t>::type flint::expression<Derived, Operation, Data>::evaluate() const [with Derived = flint::derived_wrapper<flint::fmpqxx_expression>; Operation = flint::operations::dedekind_sum_coprime_large_op; Data = flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> >; typename flint::traits::make_const<typename flint::detail::evaluation_traits<Operation, flint::expression<Derived, Operation, Data>, Data>::evaluation_return_t>::type = const flint::fmpqxx_expression<flint::operations::immediate, flint::detail::fmpq_data>]'
/builddir/build/BUILD/flint2/flintxx/expression.h:313:69:   required from 'bool flint::expression<Derived, Operation, Data>::equals(const T&, typename flint::mp::disable_if<flint::traits::is_lazy_expr<T> >::type*) const [with T = flint::fmpqxx_expression<flint::operations::immediate, flint::detail::fmpq_data>; Derived = flint::derived_wrapper<flint::fmpqxx_expression>; Operation = flint::operations::dedekind_sum_coprime_large_op; Data = flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> >; typename flint::mp::disable_if<flint::traits::is_lazy_expr<T> >::type = void]'
/builddir/build/BUILD/flint2/flintxx/expression.h:307:22:   required from 'bool flint::expression<Derived, Operation, Data>::equals(const T&, typename flint::mp::enable_if<flint::traits::is_lazy_expr<T> >::type*) const [with T = flint::fmpqxx_expression<flint::operations::dedekind_sum_op, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > >; Derived = flint::derived_wrapper<flint::fmpqxx_expression>; Operation = flint::operations::dedekind_sum_coprime_large_op; Data = flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> >; typename flint::mp::enable_if<flint::traits::is_lazy_expr<T> >::type = void]'
/builddir/build/BUILD/flint2/flintxx/expression.h:491:19:   required from 'typename flint::mp::enable_if<flint::traits::is_expression<T>, bool>::type flint::operator==(const Expr1&, const Expr2&) [with Expr1 = flint::fmpqxx_expression<flint::operations::dedekind_sum_coprime_large_op, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > >; Expr2 = flint::fmpqxx_expression<flint::operations::dedekind_sum_op, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > >; typename flint::mp::enable_if<flint::traits::is_expression<T>, bool>::type = bool]'
test/t-arithxx.cpp:169:5:   required from here
/builddir/build/BUILD/flint2/arithxx.h:67:21: error: 'fmpq_dedekind_sum_coprime_large' was not declared in this scope; did you mean 'arith_dedekind_sum_coprime_large'?
   67 |         arith_##name(detail::extract_data(to), detail::extract_data(e1), \
/builddir/build/BUILD/flint2/flintxx/rules.h:359:9: note: in definition of macro 'FLINT_DEFINE_BINARY_EXPR_COND2'
  359 |         eval; \
      |         ^~~~
/builddir/build/BUILD/flint2/arithxx.h:274:1: note: in expansion of macro 'ARITHXX_DEFINE_BINOP'
  274 | ARITHXX_DEFINE_BINOP(dedekind_sum_coprime_large, fmpqxx,
      | ^~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/flint2/arithxx.h: In instantiation of 'static void flint::rules::binary_expression<T, flint::operations::dedekind_sum_coprime_op, U, typename flint::mp::enable_if<flint::mp::and_<flint::flint_classes::is_source_base<flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data> >::type<T>, flint::flint_classes::is_source_base<flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data> >::type<U> > >::type>::doit(V&, const T&, const U&) [with V = flint::fmpqxx_expression<flint::operations::immediate, flint::detail::fmpq_data>; T = flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>; U = flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>]':
/builddir/build/BUILD/flint2/flintxx/default_rules.h:98:24:   required from 'static void flint::rules::rdetail::binary_expr_helper<BE, Data1, Op, Data2>::doit(const data_t&, flint::rules::rdetail::binary_expr_helper<BE, Data1, Op, Data2>::temporaries_t, Return*) [with Return = flint::fmpqxx_expression<flint::operations::immediate, flint::detail::fmpq_data>; BE = flint::rules::binary_expression; Data1 = const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&; Op = flint::operations::dedekind_sum_coprime_op; Data2 = const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&; flint::rules::rdetail::binary_expr_helper<BE, Data1, Op, Data2>::data_t = flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> >; flint::rules::rdetail::binary_expr_helper<BE, Data1, Op, Data2>::temporaries_t = flint::empty_tuple]'
/builddir/build/BUILD/flint2/flintxx/expression.h:76:26:   required from 'static void flint::detail::evaluation_traits<Operation, Expr, Data>::evaluate_into_fresh(flint::detail::evaluation_traits<Operation, Expr, Data>::evaluation_return_t&, const derived_t&) [with Operation = flint::operations::dedekind_sum_coprime_op; Expr = flint::expression<flint::derived_wrapper<flint::fmpqxx_expression>, flint::operations::dedekind_sum_coprime_op, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > >; Data = flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> >; flint::detail::evaluation_traits<Operation, Expr, Data>::evaluation_return_t = flint::fmpqxx_expression<flint::operations::immediate, flint::detail::fmpq_data>; flint::detail::evaluation_traits<Operation, Expr, Data>::derived_t = flint::fmpqxx_expression<flint::operations::dedekind_sum_coprime_op, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > >]'
/builddir/build/BUILD/flint2/flintxx/expression.h:49:28:   required from 'static flint::detail::evaluation_traits<Operation, Expr, Data>::evaluation_return_t flint::detail::evaluation_traits<Operation, Expr, Data>::evaluate(const derived_t&) [with Operation = flint::operations::dedekind_sum_coprime_op; Expr = flint::expression<flint::derived_wrapper<flint::fmpqxx_expression>, flint::operations::dedekind_sum_coprime_op, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > >; Data = flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> >; flint::detail::evaluation_traits<Operation, Expr, Data>::evaluation_return_t = flint::fmpqxx_expression<flint::operations::immediate, flint::detail::fmpq_data>; flint::detail::evaluation_traits<Operation, Expr, Data>::derived_t = flint::fmpqxx_expression<flint::operations::dedekind_sum_coprime_op, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > >]'
/builddir/build/BUILD/flint2/flintxx/expression.h:275:37:   required from 'typename flint::traits::make_const<typename flint::detail::evaluation_traits<Operation, flint::expression<Derived, Operation, Data>, Data>::evaluation_return_t>::type flint::expression<Derived, Operation, Data>::evaluate() const [with Derived = flint::derived_wrapper<flint::fmpqxx_expression>; Operation = flint::operations::dedekind_sum_coprime_op; Data = flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> >; typename flint::traits::make_const<typename flint::detail::evaluation_traits<Operation, flint::expression<Derived, Operation, Data>, Data>::evaluation_return_t>::type = const flint::fmpqxx_expression<flint::operations::immediate, flint::detail::fmpq_data>]'
/builddir/build/BUILD/flint2/flintxx/expression.h:313:69:   required from 'bool flint::expression<Derived, Operation, Data>::equals(const T&, typename flint::mp::disable_if<flint::traits::is_lazy_expr<T> >::type*) const [with T = flint::fmpqxx_expression<flint::operations::immediate, flint::detail::fmpq_data>; Derived = flint::derived_wrapper<flint::fmpqxx_expression>; Operation = flint::operations::dedekind_sum_coprime_op; Data = flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> >; typename flint::mp::disable_if<flint::traits::is_lazy_expr<T> >::type = void]'
/builddir/build/BUILD/flint2/flintxx/expression.h:307:22:   required from 'bool flint::expression<Derived, Operation, Data>::equals(const T&, typename flint::mp::enable_if<flint::traits::is_lazy_expr<T> >::type*) const [with T = flint::fmpqxx_expression<flint::operations::dedekind_sum_op, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > >; Derived = flint::derived_wrapper<flint::fmpqxx_expression>; Operation = flint::operations::dedekind_sum_coprime_op; Data = flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> >; typename flint::mp::enable_if<flint::traits::is_lazy_expr<T> >::type = void]'
/builddir/build/BUILD/flint2/flintxx/expression.h:491:19:   required from 'typename flint::mp::enable_if<flint::traits::is_expression<T>, bool>::type flint::operator==(const Expr1&, const Expr2&) [with Expr1 = flint::fmpqxx_expression<flint::operations::dedekind_sum_coprime_op, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > >; Expr2 = flint::fmpqxx_expression<flint::operations::dedekind_sum_op, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > >; typename flint::mp::enable_if<flint::traits::is_expression<T>, bool>::type = bool]'
test/t-arithxx.cpp:170:5:   required from here
/builddir/build/BUILD/flint2/arithxx.h:67:21: error: 'fmpq_dedekind_sum_coprime' was not declared in this scope; did you mean 'fmpq_dedekind_sum_naive'?
   67 |         arith_##name(detail::extract_data(to), detail::extract_data(e1), \
/builddir/build/BUILD/flint2/flintxx/rules.h:359:9: note: in definition of macro 'FLINT_DEFINE_BINARY_EXPR_COND2'
  359 |         eval; \
      |         ^~~~
/builddir/build/BUILD/flint2/arithxx.h:276:1: note: in expansion of macro 'ARITHXX_DEFINE_BINOP'
  276 | ARITHXX_DEFINE_BINOP(dedekind_sum_coprime, fmpqxx,
      | ^~~~~~~~~~~~~~~~~~~~
make[1]: *** [../Makefile.subdirs:88: ../build/flintxx/test/t-arithxx] Error 1
```

**Comment by wbhart** [comment] 2020-05-06 16:04
Thanks for reporting it. I assume someone very recently renamed a function, or added a new function in an incomplete manner. We'll track it down and rectify it as soon as we can.

@tthsqe12 and @fredrik-johansson do you know what this should be set to? I can't find any such function.

**Comment by tthsqe12** [comment] 2020-05-06 16:08
Oh dear. It looks like flintxx was using some stuff I removed.

**Comment by wbhart** [comment] 2020-05-06 16:11
... said the helicopter engineer. :-)

**Comment by tthsqe12** [comment] 2020-05-06 16:16
Looks like we can get rid of the middle two functions here?
```
ARITHXX_DEFINE_BINOP(dedekind_sum_naive, fmpqxx,
        FMPZXX_COND_S, FMPZXX_COND_S)
ARITHXX_DEFINE_BINOP(dedekind_sum_coprime_large, fmpqxx,
        FMPZXX_COND_S, FMPZXX_COND_S)
ARITHXX_DEFINE_BINOP(dedekind_sum_coprime, fmpqxx,
        FMPZXX_COND_S, FMPZXX_COND_S)
ARITHXX_DEFINE_BINOP(dedekind_sum, fmpqxx,
        FMPZXX_COND_S, FMPZXX_COND_S)
```

**Comment by wbhart** [comment] 2020-05-06 16:28
Seems like the easiest solution. You've replaced these with "better" implementations, I presume?

Perhaps @fredrik-johansson can comment on that.

**Comment by tthsqe12** [comment] 2020-05-06 16:36
I did also got rid of the implementation using doubles `fmpq_dedekind_sum_coprime_d`

**Comment by fredrik-johansson** [comment] 2020-05-06 16:39
Yes, there's no reason for the C++ wrapper to wrap specific implementation functions... especially deleted ones :-)

**Comment by wbhart** [comment] 2020-05-06 16:43
So long as the deletion isn't a performance regression, or a suppression of the truth or causing a recession. At least that is my impression.

**Comment by tthsqe12** [comment] 2020-05-06 16:51
Ok. I will time the old implementation with doubles in its applicable range.

**Comment by wbhart** [comment] 2020-05-12 16:37
Fixed in trunk.

**Closed by wbhart** 2020-05-12 16:37 UTC
