### ISSUE TITLE
/usr/bin/ld: -r and -pie may not be used together

### ISSUE THREAD

**Issue by videlec** [wbhart/flint2#400] opened 2017-10-21 17:52 UTC
As in https://github.com/fredrik-johansson/arb/issues/181 the following cocktail
```
$ ld --version
GNU ld (GNU Binutils) 2.29
$ gcc --version
gcc (GCC) 7.2.0
```
leads to the following error in the compilation
```
/usr/bin/ld: -r and -pie may not be used together
```

**Comment by wbhart** [comment] 2017-10-21 18:55
We are aware of this issue, but we don't know how to fix it. Patches
welcome. When I looked into the documentation, it seemed that options that
are not allowed are actually required on some systems.

**Comment by defeo** [comment] 2017-10-31 16:11
Following the advice given here https://wiki.ubuntu.com/SecurityTeam/PIE, I edited `Makefile.subdirs`, and make was happy again:

```
diff --git a/Makefile.subdirs b/Makefile.subdirs
index ec05fb045..f2d8b376a 100644
--- a/Makefile.subdirs
+++ b/Makefile.subdirs
@@ -59,7 +59,7 @@ $(BUILD_DIR)/$(MOD_DIR)_%.o: %.c
        $(QUIET_CC) $(CC) $(CFLAGS) $(INCS) -c $< -o $@ -MMD -MP -MF "$(BUILD_DIR)/$(MOD_DIR)_$*.d" -MT "$(BUILD_DIR)/$(MOD_DIR)_$*.d" -MT "$@"
 
 $(MOD_LOBJ): $(LOBJS)
-       $(QUIET_CC) $(CC) $(ABI_FLAG) -Wl,-r $^ -o $@ -nostdlib
+       $(QUIET_CC) $(CC) $(ABI_FLAG) -r $^ -o $@ -nostdlib
 
 -include $(LOBJS:.lo=.d)
```

I don't understand the fix, though. The `-r` option to gcc is not documented.

**Comment by wbhart** [comment] 2017-10-31 21:07
Yes, I also don't understand the fix. I consider the entire issue unresolved, which is why I haven't merged the  patch. I won't merge security patches I don't understand, or that aren't documented.

**Comment by fredrik-johansson** [comment] 2017-11-01 19:47
It's just some random linker flags that are needed in whichever combination for whatever reason someone thought was a good idea in 1989. If the patch works on the systems we currently have available to test on, we should just apply it until someone complains or finds a better solution.

**Comment by wbhart** [comment] 2017-11-01 21:04
The reason the gcc flag -r is not documented is because it is not a gcc
flag, which is precisely why it is passed as it is, instead of the way that
is suggested in the patch.

The "patch" wasn't needed before, so it shouldn't be needed now. In short,
I don't consider this a Flint bug, and I most certainly don't see why the
patch should be considered valid.

The -no-pie option looks more reasonable to me, if only all gcc versions
supported it. If someone could supply me with a patch to turn it off only
on gcc versions that supported turning it off, I'd probably merge it.

The information at the Ubuntu link gives no rationale for Position
Independent Executables, other than it increases the effectiveness of
Address Space Layout Randomization on certain platforms. Does this mean my
older Ubuntu is insecure? Do number theory libraries need to care about
this? Or is it only relevant to crypto and security software?

I want to emphasise that under no circumstances should Flint be considered
"secure".

**Comment by fredrik-johansson** [comment] 2017-11-27 15:39
I somewhat understand the rationale for distributions switching to -pie by default. Even though that rationale does not apply to us, we have to accept that it's happening. I don't care much which way it's done, but I don't see the harm in trying Luca's patch. We have evidence that the current code is broken and this affects a large group of Ubuntu users; we have no evidence that the patch will break other systems. If it does break other systems, people will complain and then we'll have to find another solution.

**Comment by wbhart** [comment] 2017-12-05 14:23
On 27 November 2017 at 16:39, Fredrik Johansson <notifications@github.com>
wrote:

> I somewhat understand the rationale for distributions switching to -pie by
> default. Even though that rationale does not apply to us, we have to accept
> that it's happening. I don't care much which way it's done, but I don't see
> the harm in trying Luca's patch. We have evidence that the current code is
> broken and this affects a large group of Ubuntu users; we have no evidence
> that the patch will break other systems. If it does break other systems,
> people will complain and then we'll have to find another solution.
>

It seems clang passes -r to the linker. But it doesn't seem to accept
arguments.

https://clang.llvm.org/docs/ClangCommandLineReference.html

**Comment by tal-botvinnik** [comment] 2018-10-16 17:52
I confirm that the issue still arises. 
And Luca's removal of -Wl does allow the make procedure to complete.

**Comment by Foivos** [comment] 2019-04-04 20:50
This issue once more occurred for me, and removing -Wl also fixed the problem. Please make this easier to resolve, this thread was not the easiest to find and having to manually edit a file feels hacky at best.

**Comment by w-bruns** [comment] 2019-09-24 12:02
I think it does not matter who is responsible for the problem. It is an obstruction to install Flint smoothly on many (not so) new systems, and it should disappear. As far as I can see, the arb Makefile.subdirs has only -r and no -Wl,-r (anymore).

**Comment by wbhart** [comment] 2019-09-24 12:18
Actually it looks like the -r option is now documented for gcc:

https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html#index-r

So it looks like we can now apply this patch.

**Comment by wbhart** [comment] 2019-09-24 12:20
Hmm, except that the person who proposed the patch no longer seems to think it is valid:

https://github.com/wbhart/flint2/pull/305

(see comments from the patch author).

I think we still have to wait until the community resolves this problem properly. If someone can point me to a completely working solution, I will now merge it.

**Comment by edgarcosta** [comment] 2020-02-01 17:18
@wbhart, it looks like you already have applied the patch in 2017
https://github.com/wbhart/flint2/commit/b936607bda6a18bf0b85fddff323bd18ec534011

**Comment by wbhart** [comment] 2020-02-04 13:00
Yes, but people are still complaining that it is causing problems for them and that Lucas' patch fixes it for them.

And the original proposer of the patch says they have investigated and found that there is a better solution. The whole thing obviously needs proper investigation for the release. I'm not going to push a particular fix into the release without understanding it, and being able to fully defend our decision.

I think both the -r and --no-pie options will cause problems for some users. So this seems like a lose-lose to me.

**Comment by wbhart** [comment] 2020-04-10 10:36
Is there anyone who still claims this is an issue for them in trunk (since 2017), as opposed to the latest release? @edgarcosta 

If not, I will close this issue, finally, as I can confirm that we now apply the same patch in trunk as recommended by the debian people.

**Comment by defeo** [comment] 2020-04-10 12:34
Not an issue for me in trunk. I confirm this is still an issue in 2.5.2 on Arch with gcc 9.3.0 and ld 2.34.

**Comment by wbhart** [comment] 2020-04-10 12:48
Then I think I will close this, as 2.6.0 is nearly out and it has since been fixed.

**Closed by wbhart** 2020-04-10 12:48 UTC
